### ISSUE TITLE
is there any way to fix this ? 

### ISSUE THREAD

**Issue by aniel300** [VFrontDe/ESXi-Customizer-PS#17]
am trying to add custom vibs into esxi 7 but am getting this errors, is there any way to fix them ? 
![powershell_ROwyOsfNAI](https://user-images.githubusercontent.com/7571729/82912770-769b5680-9f3b-11ea-8ab2-f1355dc033ea.png)

**Comment by Protheus23** [comment]
I have the same Problem: .\ESXi-Customizer-PS-v2.8.0.ps1 -v70 -vft -load sata-xahci,net55-r8168

![Screenshot - 2020-06-11 22_18_24-aquasuite-X 13 Desktop](https://user-images.githubusercontent.com/60545975/84435107-843a2700-ac31-11ea-9d90-0847d9b35fb3.png)

**Comment by anjia0532** [comment]
I have the same Problem too. by 7.0

**Comment by VFrontDe** [comment]
No, there is no way to fix this. The net55-r8168 driver is not compatible with ESXi 7.0. There is currently no Realtek driver available for 7.0.
