### ISSUE TITLE
An unexpected error occurred: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by KashifHK123** [VFrontDe/ESXi-Customizer-PS#18]
Running with PowerShell version 5.1 and VMware PowerCLI version .. build

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-6.7.0-20200604001-standard ...
(Dated 06/04/2020 02:20:40, AcceptanceLevel: PartnerSupported,
No Doc)

Exporting the Imageprofile to 'F:\kashif\ESXi-6.7.0-20200604001-standard.iso'. Please be patient ...

**An unexpected error occurred:
[WinError 10054] An existing connection was forcibly closed by the remote host

If requesting support please be sure to include the log file
   C:\Users\DABOO\AppData\Local\Temp\ESXi-Customizer-PS-2788.log**

[ESXi-Customizer-PS-2788.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/4906124/ESXi-Customizer-PS-2788.log)

**Comment by virtualex-itv** [comment]
If a WinError 10054 is encountered, run the following commands then reboot your machine and retry:

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Ssl3`

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12`

**Comment by KashifHK123** [comment]
> If a WinError 10054 is encountered, run the following commands then reboot your machine and retry:
> 
> `[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Ssl3`
> 
> `[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12`

Issue Still Present Now I'm Getting This message

```
PS F:\kashif> .\ESXi-Customizer-PS.ps1 -v67

This is ESXi-Customizer-PS Version 2.8.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Logging to C:\Users\DABOO\AppData\Local\Temp\ESXi-Customizer-PS-14264.log ...

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-6.7.0-20200604001-standard ...
(Dated 06/04/2020 02:20:40, AcceptanceLevel: PartnerSupported,
No Doc)

Exporting the Imageprofile to 'F:\kashif\ESXi-6.7.0-20200604001-standard.iso'. Please be patient ...



An unexpected error occurred:
[WinError 10054] An existing connection was forcibly closed by the remote host

If requesting support please be sure to include the log file
   C:\Users\DABOO\AppData\Local\Temp\ESXi-Customizer-PS-14264.log
```

[ESXi-Customizer-PS-14264.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/4907975/ESXi-Customizer-PS-14264.log)

**Comment by KashifHK123** [comment]
@virtualex-itv i'm waiting for answer.

**Comment by virtualex-itv** [comment]
this issue has previously been reported and is being tracked here. ([#15](https://github.com/VFrontDe/ESXi-Customizer-PS/issues/15#issue-609129562))
