### ISSUE TITLE
An unexpected error occured:  Calculated digest at EOF does not match expected result ....expected..

### ISSUE THREAD

**Issue by cddisk2000** [VFrontDe/ESXi-Customizer-PS#19]
I Make Esxi 6.7U3 Version following steps

OS System: Server 2012 R2 9600

Step 1: Install「Windows Management Framework 5.0」

Step 2: Run「Powershell」Use Admin

Step 3: Run  =>  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 

Step 4: Run  =>  Install-PackageProvider -Name NuGet

Step 5: Run  =>  Install-Module -Name VMware.PowerCLI -RequiredVersion 10.2.0.9372002

Step 6: Run  =>  Get-Module VM* -ListAvailable

Step 7: Run  => 

[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Ssl3
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

Step 8: Disable Firewalld

Step 9: Use PowerCLI Command Line

And Then Have Error On This Log 
[ESXi-6.7.0-20200604001-standard-customized-202007111109.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/4906202/ESXi-6.7.0-20200604001-standard-customized-202007111109.log)

**Comment by VFrontDe** [comment]
net51-r8169 cannot be added to ESXi 6.7, because it is not compatible. Please check ESXi version compatibility at https://vibsdepot.v-front.de
