### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by praval1983** [VFrontDe/ESXi-Customizer-PS#22]
[ESXi-Customizer-PS.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/4929001/ESXi-Customizer-PS.log)

**Comment by virtualex-itv** [comment]
Duplicate issue, this has already been reported ([#15](https://github.com/VFrontDe/ESXi-Customizer-PS/issues/15))
