### ISSUE TITLE
Error when hit -> ESXi-Customizer-PS.ps1 -help

### ISSUE THREAD

**Issue by sungleong** [VFrontDe/ESXi-Customizer-PS#26]
Hit error when excuting below statement,

ParserError: C:\Temp\ESXi-Customizer-PS.ps1:175
Line |
 175 |  … ata-ga-click="(Logged out) Header, go to Features">Features <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.

I am using PowerShell 7.0.3 under Windows 10Home 64bits

**Comment by TheClaw0815** [comment]
Hi,

same error messages (sorry in german) with the parameter help.

In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:146 Zeichen:21
+                 Sign&nbsp;up
+                     ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:173 Zeichen:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:173 Zeichen:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:187 Zeichen:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:187 Zeichen:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:188 Zeichen:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:188 Zeichen:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:211 Zeichen:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:211 Zeichen:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:214 Zeichen:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

Same thing to build an image.

.\ESXi-Customizer-PS.ps1 -v67 -pkgDir 'C:\Users\<username>\Downloads\ESXCustom\' -outDir 'C:\Users\<username>\Downloads\ESXCustom\' -vft -nsc -log 'C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-Log.log' -load net55-r8168,esx-tools-for-esxi,esx-ui,sata-xahci,esxcli-shell,vmware-esx-dvfilter-maclearn

In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:146 Zeichen:21
+                 Sign&nbsp;up
+                     ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:173 Zeichen:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:173 Zeichen:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:187 Zeichen:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:187 Zeichen:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:188 Zeichen:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:188 Zeichen:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:211 Zeichen:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:211 Zeichen:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\<username>\Downloads\ESXCustom\ESXi-Customizer-PS.ps1:214 Zeichen:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

Conditions:

Windows 10 Professional (German)
Powershell: 5.1 (5.1.19041.1)
with PowerCLI: 12.0.0.15939655
Script Download from GitHub: 15/08/2020

Thx alot for an feedback.

**Comment by TheClaw0815** [comment]
I think it is an formatting / unicode problem. In Powershell ISE it throws many formatting errors in the HTML Code (for example &nbsp;). If i fix some rows it shows me the next one. :-(

**Comment by illki** [comment]
same, but I have a lot of those
`PS C:\> .\ESXi-Customizer-PS.ps1 -v67 -pkgDir C:\temp\pkg -nsc

Предупреждение о безопасности
Запускайте только сценарии, которым вы доверяете. Хотя сценарии из Интернета могут быть полезными, данный сценарий потенциально опасен для компьютера. Если вы
доверяете ему, разрешите его выполнение без вывода предупреждающих сообщений, выполнив командлет Unblock-File. Вы хотите запустить C:\ESXi-Customizer-PS.ps1?
[D] Не запускать - D  [R] Запустить однажды - R  [S] Приостановить - S  [?] Справка (значением по умолчанию является "D"): r
C:\ESXi-Customizer-PS.ps1:151 знак:21
+                 Sign&nbsp;up
+                     ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
C:\ESXi-Customizer-PS.ps1:178 знак:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
Оператор "<" зарезервирован для использования в будущем.
C:\ESXi-Customizer-PS.ps1:178 знак:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
C:\ESXi-Customizer-PS.ps1:192 знак:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
Оператор "<" зарезервирован для использования в будущем.
C:\ESXi-Customizer-PS.ps1:192 знак:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
C:\ESXi-Customizer-PS.ps1:193 знак:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
Оператор "<" зарезервирован для использования в будущем.
C:\ESXi-Customizer-PS.ps1:193 знак:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
C:\ESXi-Customizer-PS.ps1:216 знак:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
Оператор "<" зарезервирован для использования в будущем.
C:\ESXi-Customizer-PS.ps1:216 знак:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
C:\ESXi-Customizer-PS.ps1:219 знак:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
Амперсанд (&) не разрешен. Оператор & зарезервирован для будущих версий. Добавьте двойные кавычки до и после амперсанда ("&"), чтобы передать его как строку.
Выданы сообщения не обо всех ошибках синтаксического анализа.  Исправьте перечисленные в сообщениях ошибки и повторите попытку.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\>`

PSVersion 5.1.19041.1
VMware PowerCLI 12.0.0 build 15947286

**Comment by virtualex-itv** [comment]
Doesn't appear to be an issue with the script as I am unable to reproduce this issue.

```
PS C:\Users\virtualex\Documents> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      3

PS C:\Users\virtualex\Documents> Get-Module -Name VMware.PowerCLI -ListAvailable | Format-Table -AutoSize


    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version         PreRelease Name            PSEdition ExportedCommands
---------- -------         ---------- ----            --------- ----------------
Manifest   12.0.0.15947286            VMware.PowerCLI Desk


PS C:\Users\virtualex\Documents> .\ESXi-Customizer-PS.ps1 -help

This is ESXi-Customizer-PS Version 2.8.1 (visit https://ESXi-Customizer-PS.v-front.de for more information!)

Usage:
  ESXi-Customizer-PS [-help] |  [-izip <bundle> [-update]] [-sip] [-v70|-v67|-v65|-v60|-v55|-v51|-v50]
                                [-ozip] [-pkgDir <dir>[,...]] [-outDir <dir>] [-vft] [-dpt depot1[,...]]
                                [-load vib1[,...]] [-remove vib1[,...]] [-log <file>] [-ipname <name>]
                                [-ipdesc <desc>] [-ipvendor <vendor>] [-nsc] [-test]

Optional parameters:
   -help              : display this help
   -izip <bundle>     : use the VMware Offline bundle <bundle> as input instead of the Online depot
   -update            : only with -izip, updates a local bundle with an ESXi patch from the VMware Online depot,
                        combine this with the matching ESXi version selection switch
   -pzip              : use an Offline patch bundle instead of the Online depot with -update.
   -pkgDir <dir>[,...]: local directories of Offline bundles and/or VIB files to add (if any, no default)
   -ozip              : output an Offline bundle instead of an installation ISO
   -outDir <dir>      : directory to store the customized ISO or Offline bundle (the default is the
                        script directory. If specified the log file will also be moved here.)
   -vft               : connect the V-Front Online depot
   -dpt depot1[,...]  : connect additional Online depots by URL or local Offline bundles by file name
   -load vib1[,...]   : load additional packages from connected depots or Offline bundles
   -remove vib1[,...] : remove named VIB packages from the custom Imageprofile
   -sip               : select an Imageprofile from the current list
                        (default = auto-select latest available standard profile)
   -v70 |
   -v67 | -v65 | -v60 |
   -v55 | -v51 | -v50 : Use only ESXi 7.0/6.7/6.5/6.0/5.5/5.1/5.0 Imageprofiles as input, ignore other versions
   -nsc               : use -NoSignatureCheck with export
   -log <file>        : Use custom log file <file>
   -ipname <name>
   -ipdesc <desc>
   -ipvendor <vendor> : provide a name, description and/or vendor for the customized
                        Imageprofile (the default is derived from the cloned input Imageprofile)
   -test              : skip package download and image build (for testing)
```
