### ISSUE TITLE
can't add network card for esxi 6.7u3b

### ISSUE THREAD

**Issue by carlsue** [VFrontDe/ESXi-Customizer-PS#28]
警告: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
警告:   File path of '/etc/vmware/driver.map.d/sky2-1.map' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733'}
警告:   File path of '/etc/vmware/driver.map.d/r8169.map' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733',
'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733'}
警告:   File path of '/usr/share/hwdata/driver.pciids.d/r8169.ids' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733',
'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733'}
警告:   File path of '/usr/lib/vmware/vmkmod/r8169' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733',
'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733'}
警告:   File path of '/etc/vmware/driver.map.d/r8168.map' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'Realtek_bootbank_net55-r8168_8.045a-napi'}
警告:   File path of '/usr/lib/vmware/vmkmod/r8168' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'Realtek_bootbank_net55-r8168_8.045a-napi'}
警告:   File path of '/etc/vmware/driver.map.d/sky2.map' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733'}
警告:   File path of '/usr/share/hwdata/driver.pciids.d/sky2.ids' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733'}
警告:   File path of '/usr/lib/vmware/vmkmod/sky2' is claimed by multiple non-overlay VIBs: {'VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733',
'VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733'}
警告:   VIB VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIBs (Realtek_bootbank_net55-r8168_8.045a-napi, VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733) are conflicting with each other
警告:   VIB VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIBs (Realtek_bootbank_net55-r8168_8.045a-napi, VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733, VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733,
VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733) are conflicting with each other
警告:   VIB Realtek_bootbank_net-r8101_1.020.00-1 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB SysKonnect_bootbank_net-skge_1.13-1 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Realtek_bootbank_net-r8139too_0.9.28-1 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Realtek_bootbank_net-r8139too_0.9.28-1 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB GLRoman_bootbank_net-e1000e_3.1.0.2-glr2 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Atheros_bootbank_net-atl1e_1.0.1.14-1 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB GLRoman_bootbank_net-e1000e_3.1.0.2-glr2 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Atheros_bootbank_net-atl1e_1.0.1.14-1 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Atheros_bootbank_net-atl1_2.1.3-1 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIBs (VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733, VFrontDe_bootbank_net51-r8169_6.011.00-2vft.510.0.0.799733) are conflicting with each other
警告:   VIBs (VFrontDe_bootbank_net51-drivers_1.1.0-1vft.510.0.0.799733, VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733) are conflicting with each other
警告:   VIB SysKonnect_bootbank_net-skge_1.13-1 requires com.vmware.driverAPI-9.2.0.0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Atheros_bootbank_net-atl1_2.1.3-1 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB VFrontDe_bootbank_net51-sky2_1.20-2vft.510.0.0.799733 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB DEC_bootbank_net-tulip_1.1.15-1 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.
警告:   VIB Realtek_bootbank_net-r8101_1.020.00-1 requires vmkapi_2_0_0_0, but the requirement cannot be satisfied within the ImageProfile.

All done.

**Comment by carlsue** [comment]
powershell cli:
.\ESXi-Customizer-PS.ps1 -izip .\ESXi670-201912001.zip -pkgDir C:\Users\xxx\Downloads\VMware\pkg

**Comment by virtualex-itv** [comment]
The reason for the error is because these are legacy realtek drivers that were initially created for and compatible with versions 5.x.  These are no longer supported in 6.x and above...  Recommendation is to replace NIC with an Intel Card.
