### ISSUE TITLE
"[WinError 10054] An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by iSnackyCracky** [VFrontDe/ESXi-Customizer-PS#31]
Hey folks,

I know there already exists Issue #15 but the communication on this is restricted to collaborators and I wanted to add some information. (Also, it still has the "wontfix" label, I'm not sure if this is still correct because it was added before the issue got reopened.)

I ran into basically the same issue today while trying to create a basic ESXi 7.0 image (without any parameters).

I've tried both the [Net.ServicePointManager]::SecurityProtocol, aswell as the Registry modifications (SchUseStrongCrypto - which, if I understand this correctly, basically does the opposite as setting the SecurityProtocol to SSL3)

Neither of these options worked for me.

The workaround mentioned by @crapsterNET (using the -ozip and then izip parameters) worked for me, but it seems this shouldn't have to be necessary.
If this is the only reliable workaround, I would suggest implementing this in the script itself (basically combine these steps using a temporary location or something like that). That way the user doesn't need to execute these steps by himself and instead the script just handles this.

**Comment by BeaNs-au** [comment]
I haven't tried the options laid out in the other thread regarding SSL3 Net Protocol, but i was just able to finally get it working by running the script to create a bundle and inject the driver and then convert to ISO.
So for me -
Step 1 - ESXi-Customizer-PS.ps1 -ozip -v67 -vft -load net55-r8168
once completed
Step 2 - ESXi-Customizer-PS.ps1 -izip ESXi-6.7.0-20200804001-standard-customized.zip

**Comment by virtualex-itv** [comment]
Hi @iSnackyCracky - thanks for your comments.  Not sure why this is happening but it's not something that can be fixed in the script as it's not a "script-related issue" but rather an issue with the site that the script reaches out to communicate with.  The site still requires `Ssl3` for whatever reason.  I've run the command to enable Ssl3 on a fresh windows install as well as an old windows machine, followed by a system reboot and then the script worked just fine.

**Comment by iSnackyCracky** [comment]
Thanks for the quick response @virtualex-itv, thing is: I tried this on another machine today:
Windows 10 Version 2004 (Build 19041.450), not a clean install but upgraded from around Win10 v1903 or so.
PSVersion 5.1.19041.1
VMware.PowerCLI Module Version 12.0.0.15947286

`[Net.ServicePointManger]::SecurityProtocol` returns `Tls12`

And the script just works.

I'm not completely sure and I can't currently try the first machine again, but I think the PowerCLI Module Version installed there was 11.0.something


@BeaNs-au yeah, as I said - using -ozip followed by -izip worked for me too (but I think this should really only be used/needed to do manually as a last workaround).

**Comment by virtualex-itv** [comment]
Yea I noticed that on my fresh install, it worked without any system modifications.  Then, the next day, I received the 10054 Error.  Once I ran the command from and elevated shell to enable `Ssl3` and rebooted the system via `Restart-Computer`, I was able to run the script again successfully on said system.  Could be a PowerShell issue but I am not truly sure. “¯\_(ツ)_/¯“

**Comment by virtualex-itv** [comment]
FYI - a possible solution is being tested.

**Comment by d666anggel** [comment]
> 
> 
> I haven't tried the options laid out in the other thread regarding SSL3 Net Protocol, but i was just able to finally get it working by running the script to create a bundle and inject the driver and then convert to ISO.
> So for me -
> Step 1 - ESXi-Customizer-PS.ps1 -ozip -v67 -vft -load net55-r8168
> once completed
> Step 2 - ESXi-Customizer-PS.ps1 -izip ESXi-6.7.0-20200804001-standard-customized.zip

This is work for me. Thank you.

**Comment by virtualex-itv** [comment]
possible solution has been undergoing testing but it's still hit or miss, nothing that we can truly fix as it's not an issue with the script.  Current w/a is to export as a .zip then import said .zip to create a .iso.
