### ISSUE TITLE
Latest Script 2.8.1 causes errors on win 10 2004 (Powershell 5.1)

### ISSUE THREAD

**Issue by chrissi55** [VFrontDe/ESXi-Customizer-PS#33]
With the latest script version 2.8.1 i get the following errors when running the ESXi-Customizer-PS.ps1

"In C:\TEMP\ESXi-Customizer-PS.ps1:152 Zeichen:21
                 Sign&nbsp;up
                     ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\TEMP\ESXi-Customizer-PS.ps1:179 Zeichen:190
 ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\TEMP\ESXi-Customizer-PS.ps1:179 Zeichen:261
......."
 
further errors see screenshot

https://www.bilder-upload.eu/bild-398361-1602395363.png.html

I have installed the latest version of vmware powercli (12.x)
using this explanation: https://docs.vmware.com/de/VMware-vSphere/7.0/com.vmware.esxi.install.doc/GUID-F02D0C2D-B226-4908-9E5C-2E783D41FE2D.html

**Comment by chrissi55** [comment]
Tried with the Powershell 7.0.3 (pwsh)

Here the Errors are different:
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\TEMP\ESXi-Customizer-PS.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
ParserError: C:\TEMP\ESXi-Customizer-PS.ps1:157
Line |
 157 |  … etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
     |                                                                         ~
     | Missing file specification after redirection operator.

PS C:\TEMP> ./ESXi-Customizer-PS.ps1
ParserError: C:\TEMP\ESXi-Customizer-PS.ps1:352
Line |
 352 |          <svg class="octicon octicon-sign-out v-align-middle" viewBox= …
     |                      ~~~~~~~
     | Unexpected token 'octicon' in expression or statement.

https://www.bilder-upload.eu/bild-4fc08a-1603011142.png.html

**Comment by meilon** [comment]
I just successfully built an ISO from an HPE offline bundle and including updates for vSphere 7.0.

Are you sure the script downloaded successfully? It looks like there is some HTML code in your local version, which there is none in the script originally (escaped or otherwise). From the screenshot it looks like you downloaded the whole page and not the script itself. Use the file from the [releases](https://github.com/VFrontDe/ESXi-Customizer-PS/releases) or the [raw file](https://github.com/VFrontDe/ESXi-Customizer-PS/raw/master/ESXi-Customizer-PS.ps1).

**Comment by chrissi55** [comment]
Downloading the script again didn't help. But taking the raw file and building a ps1 script helped to get the script running, Thanks.

But now when using following command i get warnings:

```
`PS C:\temp> .\ESXi-Customizer-PS-v2.8.1.ps1 -v70 -vft -load sata-xahci
VMware's Customer Experience Improvement Program ("CEIP") provides VMware with information that enables VMware to
improve its products and services, to fix problems, and to advise you on how best to deploy and use our products.  As
part of the CEIP, VMware collects technical information about your organization’s use of VMware products and services
on a regular basis in association with your organization’s VMware license key(s).  This information does not personally
 identify any individual.

For more details: type "help about_ceip" to see the related help article.
To disable this warning and set your preference use the following command and restart PowerShell:
Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true or $false.

Running with PowerShell version 5.1 and VMware PowerCLI version .. build

Connecting the VMware ESXi Software depot ... [OK]

Connecting the V-Front Online depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-7.0U1sc-17325020-standard ...
(Dated 12/15/2020 10:50:21, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 7.0U1sc brings whole new levels of virtualization performance to datacenters and enterprises.)

Load additional VIBs from Online depots ...
   Add VIB sata-xahci 1.42-1 [New AcceptanceLevel: CommunitySupported] [OK, added]

Exporting the Imageprofile to 'C:\temp\ESXi-7.0U1sc-17325020-standard-customized.iso'. Please be patient ...

WARNUNG: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors
and may not boot or be functional.  Errors:
WARNUNG:   VIB VFrontDe_bootbank_sata-xahci_1.42-1 requires sata-ahci, but the requirement cannot be satisfied within
the ImageProfile. However, additional VIB(s) VMware_bootbank_sata-ahci_3.0-21vmw.600.0.0.2494585,
VMware_bootbank_sata-ahci_3.0-13vmw.510.0.0.799733, VMware_bootbank_sata-ahci_3.0-28vmw.600.3.107.10474991,
VMware_bootbank_sata-ahci_3.0-6vmw.500.1.11.623860, VMW_bootbank_sata-ahci_3.0-26vmw.650.1.26.5969303,
VMware_bootbank_sata-ahci_3.0-21vmw.600.0.11.2809209, VMware_bootbank_sata-ahci_3.0-6vmw.500.0.0.469512,
VMW_bootbank_sata-ahci_3.0-26vmw.670.0.0.8169922, VMware_bootbank_sata-ahci_3.0-15vmw.510.2.23.1483097,
VMware_bootbank_sata-ahci_3.0-22vmw.550.3.68.3029944, VMware_bootbank_sata-ahci_3.0-22vmw.600.2.34.3620759,
VMware_bootbank_sata-ahci_3.0-26vmw.600.3.57.5050593, VMware_bootbank_sata-ahci_3.0-22vmw.600.1.17.3029758,
VMware_bootbank_sata-ahci_3.0-17vmw.550.0.0.1331820, VMware_bootbank_sata-ahci_3.0-20vmw.550.2.33.2068190,
VMware_bootbank_sata-ahci_3.0-21vmw.550.2.39.2143827, VMware_bootbank_sata-ahci_3.0-27vmw.600.3.104.9919195,
VMW_bootbank_sata-ahci_3.0-22vmw.650.0.0.4564106, VMware_bootbank_sata-ahci_3.0-21vmw.550.2.54.2403361,
VMware_bootbank_sata-ahci_3.0-18vmw.550.1.15.1623387, VMware_bootbank_sata-ahci_3.0-22vmw.550.3.89.4179633 from depot
can satisfy this requirement.

All done.

PS C:\temp>
````

Booting from that image does lead into install errors because the sata-xahci driver could not be loaded properly.
How can i get rid of those errors?

**Comment by meilon** [comment]
Sorry, can't really help with that, but a quick google search brought me to this: https://anthonyspiteri.net/datastore-esxi7-upgrade-supermicro/
Maybe you don't need the community module anymore? It seems there is no sata-ahci any more in 7.0 and you should use vmw_ahci instead

**Comment by virtualex-itv** [comment]
unfortunately, you cannot add the `sata-xahci` driver to `v70`.  it is only supported on `v55` & possibly `v60` but @VFrontDe can confirm that best.
