### ISSUE TITLE
change/force the acceptance level to CommunitySupported

### ISSUE THREAD

**Issue by HellboyPI** [VFrontDe/ESXi-Customizer-PS#39]
How to change/ force the acceptance level to CommunitySupported, when using the ESXi-Customizer-PS script?

I want to create an ESXi 7 custom image with support for [Intel I219 / I225 network adapter](https://www.virtuallyghetto.com/2021/02/new-community-networking-driver-for-esxi-fling.html).

a) I downloaded the [Community Networking Driver for ESXi](https://flings.vmware.com/community-networking-driver-for-esxi).
b) Ran the command .\ESXi-Customizer-PS-v2.8.1.ps1 -pkgDir C:\scripts\driver -ozip
c) ESXi 7 custom image with the Community Networking Driver was created, but the acceptance level stayed PartnerSupported.

Or, is it possible to add the Community Networking Driver for ESXi to the V-Front Online Depot? 
The ESXi-Customizer-PS script then automatically changes the acceptance level to CommunitySupported.

**Comment by virtualex-itv** [comment]
what benefit do you get or what issues are you encountering that would require the need for `CommunitySupported`?

**Comment by HellboyPI** [comment]
Will the Community Networking Driver for ESXi work if the acceptance level is not CommunitySupported?
Community driver needs CommunitySupported acceptance level, or not?

**Comment by virtualex-itv** [comment]
I honestly cannot answer that question as it's not related to the script nor do I have a system that would leverage that driver to test on, but the driver can indeed be added to your image using the script.  I used the following command:

`.\ESXi-Customizer-PS.ps1 -v70 -sip -pkgDir .\pkg\ -outDir .\iso\ -nsc`

![2021-05-19_8-02-07](https://user-images.githubusercontent.com/12056704/118809668-e99e8b00-b878-11eb-96e2-4ceff0900f66.png)
