### ISSUE TITLE
ESXi cannot see NIC after customizer is run

### ISSUE THREAD

**Issue by JorgeCarousel** [VFrontDe/ESXi-Customizer-PS#43]
Hey guys,

I have a workstation with an Intel i210 NIC and a LSI SAS2308 RAID card on it, I found the driver (vib) for the RAID card, added it to ESXi 7 iso but when I booted it up, it did not see the NIC that it did see before when it didn't see the RAID.

Any ideas?

Thanks

**Comment by virtualex-itv** [comment]
unfortunately no, and this issue is not related to anything with the script itself.
