### ISSUE TITLE
DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by nyukers** [VFrontDe/ESXi-Customizer-PS#46]
Hi,

I try to run:
.\ESXi-Customizer-PS-v2.8.2.ps1  -sip –ozip
and choose 255 profile.

Result:

Using Imageprofile ESXi-6.0.0-20170604001-standard ...
(Dated 02/07/2020 11:36:33, AcceptanceLevel: PartnerSupported,
For more information, see http://kb.vmware.com/kb/2149958.)

Exporting the Imageprofile to 'F:\ESX\ESXi-6.0.0-20170604001-standard.zip'. Please be patient ...

PS>TerminatingError(Export-EsxImageProfile): "Unable to download from any URLs: ('https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/esx/vmw/vib20/tools-light/VMware_locker_tools-light_6.0.0-3.66.5485776.vib', 'C:\\Users\\Mikele\\AppData\\Local\\Temp\\tmp6_m0yvyp\\vib20\\tools-light\\VMware_locker_tools-light_6.0.0-3.66.5485776.vib', '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)')"
>> TerminatingError(Export-EsxImageProfile): "Unable to download from any URLs: ('https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/esx/vmw/vib20/tools-light/VMware_locker_tools-light_6.0.0-3.66.5485776.vib', 'C:\\Users\\Mikele\\AppData\\Local\\Temp\\tmp6_m0yvyp\\vib20\\tools-light\\VMware_locker_tools-light_6.0.0-3.66.5485776.vib', '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)')"

An unexpected error occurred:
Unable to download from any URLs: ('https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/esx/vmw/vib20/tools-light/VMware_locker_tools-light_6.0.0-3.66.5485776.vib', 'C:\\Users\\Mikele\\AppData\\Local\\Temp\\tmp6_m0yvyp\\vib20\\tools-light\\VMware_locker_tools-light_6.0.0-3.66.5485776.vib', '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)')

Where is my problem?

**Comment by nyukers** [comment]
I resolved issue.

**Comment by VFrontDe** [comment]
> I resolved issue.

How did you resolve the issue?
Thank you for the feedback.
