### ISSUE TITLE
cross platform compatibility is missing

### ISSUE THREAD

**Issue by chr1s386** [VFrontDe/ESXi-Customizer-PS#47]
This script wont work with PowerShell on Macos causing the paths with backslash

**Comment by VFrontDe** [comment]
The script currently requires PowerCLI on Windows, because the VMware Imgebuilder module (that it uses) has not yet been ported to PowerShell Core.
So I have not yet worried about path names etc. to be compatible with MacOS and Linux.

**Comment by chr1s386** [comment]
Ok, you are right!
