### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by sunny1025g** [VFrontDe/ESXi-Customizer-PS#48]
ESXi-6.7.0-20221004001-standard (Build 20497097)

Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ("<zipfile.ZipExtFile
 name='vib20/esx-ui/VMware_bootbank_esx-ui_1.43.10-20199807.vib' mode='r' compress_type=deflate>", "Error opening file
object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found va
lue '[<vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE34D13B08>, <vmware.esximage.Vib.SoftwarePlatform object
 at 0x000001EE34D13508>]'.").
If requesting support please be sure to include the log file.

PSVersion: 5.1.19041.1682
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1682
BuildVersion: 10.0.19041.1682
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************

Running with PowerShell version 5.1 and VMware PowerCLI version 12.7.0 build 20091289

Adding base Offline bundle .\ESXi670-202210001.zip ...
 [OK]

Getting Imageprofiles, please wait ...
 [OK]

Using Imageprofile ESXi-6.7.0-20221004001-standard ...
(Dated 09/21/2022 13:36:44, AcceptanceLevel: PartnerSupported,
Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20221004001-standard)

Exporting the Imageprofile to 'D:\esxi\ESXi-6.7.0-20221004001-standard.iso'. Please be patient ...

PS>TerminatingError(Export-EsxImageProfile):“Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ("<zipfile.ZipExtFile name='vib20/esx-ui/VMware_bootbank_esx-ui_1.43.10-20199807.vib' mode='r' compress_type=deflate>", "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F748>, <vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F9C8>]'.").”
>> TerminatingError(Export-EsxImageProfile):“Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ("<zipfile.ZipExtFile name='vib20/esx-ui/VMware_bootbank_esx-ui_1.43.10-20199807.vib' mode='r' compress_type=deflate>", "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F748>, <vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F9C8>]'.").”

An unexpected error occurred:
Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ("<zipfile.ZipExtFile name='vib20/esx-ui/VMware_bootbank_esx-ui_1.43.10-20199807.vib' mode='r' compress_type=deflate>", "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F748>, <vmware.esximage.Vib.SoftwarePlatform object at 0x000001EE3630F9C8>]'.").

If requesting support please be sure to include the log file

**Comment by virtualex-itv** [comment]
https://github.com/VFrontDe/ESXi-Customizer-PS/issues/49
