### ISSUE TITLE
Can't creat the ISO file!

### ISSUE THREAD

**Issue by imacer** [VFrontDe/ESXi-Customizer-PS#49]
lunch ".\ESXi-Customizer-PS.ps1 -nsc -iZip .\ESXi670-202210001.zip"

An unexpected error occurred:
Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ("<zipfile.ZipExtFile name='vib20/esx-ui/VMware_bootbank_esx-ui_1.43.10-20199807.vib' mode='r' compress_type=deflate>", "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x000001DFB3459708>, <vmware.esximage.Vib.SoftwarePlatform object at 0x000001DFB34599C8>]'.").

If requesting support please be sure to include the log file

**Comment by virtualex-itv** [comment]
this is not an issue with the scripts but rather being unable to retrieve the required file for VIB.  It's possible it may have been removed.
