### ISSUE TITLE
Python issue with new 2.9.0 with ESXi 8.0

### ISSUE THREAD

**Issue by Turranius** [VFrontDe/ESXi-Customizer-PS#55]
Following up on https://github.com/VFrontDe-Org/ESXi-Customizer-PS/issues/51

Never had to use Python before so a bit of a noob on that but installed it according to the instructions and ran the get-pip script.

Does not work after setting its path. Not sure what I do wrong. (Also, log file name is 280, not 290).

PS I:\Drivers\ESXi\Python3.7> .\python.exe
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

PS I:\Drivers\ESXi> cd .\Python3.7\
PS I:\Drivers\ESXi\Python3.7> .\python.exe .\get-pip.py
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
  WARNING: The scripts pip.exe, pip3.7.exe and pip3.exe are installed in 'I:\Drivers\ESXi\Python3.7\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.3.1

PS I:\Drivers\ESXi\Python3.7> Set-PowerCLIConfiguration -PythonPath I:\Drivers\ESXi\Python3.7\python.exe -Scope User

Perform operation?
Performing operation 'Update VMware.PowerCLI configuration.'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y

Scope    ProxyPolicy     DefaultVIServerMode InvalidCertificateAction  DisplayDeprecationWarnings WebOperationTimeout
                                                                                                  Seconds
-----    -----------     ------------------- ------------------------  -------------------------- -------------------
Session  UseSystemProxy  Multiple            Prompt                    True                       300
User                                         Prompt
AllUsers

PS I:\Drivers\ESXi\Python3.7> cd ..
PS I:\Drivers\ESXi> .\ESXi-Customizer-PS-v2.9.0.ps1 -v80 -outDir "I:\Drivers\ESXi\ISO2"

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Temporarily logging to C:\Users\mgr\AppData\Local\Temp\ESXi-Customizer-PS-280.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.0.0 build 20829139

Connecting the VMware ESXi Software depot ...

An unexpected error occurred:
Could not initialize the VMware.ImageBuilder PowerCLI module. Make sure that Python 3.7 is installed and that you have set the path to the Python executable by using Set-PowerCLIConfiguration -PythonPath. See the PowerCLI Compatibility Matrixes for information on the Python requirements.

If requesting support please be sure to include the log file
   C:\Users\mgr\AppData\Local\Temp\ESXi-Customizer-PS-280.log

EDIT: Forgot to add that the 4 packages are installed as well.

PS I:\Drivers\ESXi\Python3.7\Scripts> ./pip3.7.exe install six psutil lxml pyopenssl
Requirement already satisfied: six in i:\drivers\esxi\python3.7\lib\site-packages (1.16.0)
Requirement already satisfied: psutil in i:\drivers\esxi\python3.7\lib\site-packages (5.9.4)
Requirement already satisfied: lxml in i:\drivers\esxi\python3.7\lib\site-packages (4.9.1)
Requirement already satisfied: pyopenssl in i:\drivers\esxi\python3.7\lib\site-packages (22.1.0)
Requirement already satisfied: cryptography<39,>=38.0.0 in i:\drivers\esxi\python3.7\lib\site-packages (from pyopenssl) (38.0.4)
Requirement already satisfied: cffi>=1.12 in i:\drivers\esxi\python3.7\lib\site-packages (from cryptography<39,>=38.0.0->pyopenssl) (1.15.1)
Requirement already satisfied: pycparser in i:\drivers\esxi\python3.7\lib\site-packages (from cffi>=1.12->cryptography<39,>=38.0.0->pyopenssl) (2.21)

**Comment by richardrey** [comment]
I have the same problem, is there a solution?

**Comment by virtualex-itv** [comment]
This is not an issue with this script but rather with meeting the requirements for PowerCLI 13 to initialize the `VMware.ImageBuilder` module.  Please consult the VMware documentation for PowerCLI and configuring the Python path and/or reach out to VMware support.
