### ISSUE TITLE
Version 2.9.0 issues with ESXi 7.

### ISSUE THREAD

**Issue by Turranius** [VFrontDe/ESXi-Customizer-PS#56]
Following up with https://github.com/VFrontDe-Org/ESXi-Customizer-PS/issues/55 - Not sure if they are related.

After updating to 2.9.0 and VMware PowerCLI version 13.0.0 build 20829139, ESXi 7 also has problems.

.\ESXi-Customizer-PS-v2.9.0.ps1 -v70 -outDir "I:\Drivers\ESXi\ISO2"

PS>TerminatingError(Export-EsxImageProfile): "[PEM: NO_START_LINE] no start line (_ssl.c:2460)"

Log included.

[ESXi-7.0U3si-20841705-standard.iso-202212120937.log](https://github.com/VFrontDe-Org/ESXi-Customizer-PS/files/10206170/ESXi-7.0U3si-20841705-standard.iso-202212120937.log)

**Comment by Turranius** [comment]
Moving back to PowerCLI 12.7.0-20091289 and it works just fine. Both version 2.8.1 and 2.9.0 works to create an ESXi 7 ISO so probably not really your problem =) Worth a shot.

**Comment by xml111** [comment]
Actual for VMware PowerCLI version 12.7.0 build 20091289 for all ESXI:

```
\ESXi-Customizer-PS> .\ESXi-Customizer-PS.ps1 -v70

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)
Logging to ..\ESXi-Customizer-PS.log ...
Running with PowerShell version 5.1 and VMware PowerCLI version 12.7.0 build 20091289
Connecting the VMware ESXi Software depot ... [OK]
Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-7.0U3si-20841705-standard ...
(Dated 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 7.0U3si brings whole new levels of virtualization performance to datacenters and enterprises.)
Exporting the Imageprofile to '..\ESXi-7.0U3si-20841705-standard.iso'. Please be patient ...

An unexpected error occurred:
**[PEM: NO_START_LINE] no start line (_ssl.c:2460)**
If requesting support please be sure to include the log file
```

packages version:
```
Name: six
Version: 1.16.0

Name: psutil
Version: 5.9.4

Name: lxml
Version: 4.9.2

Name: pyOpenSSL
Version: 22.1.0
```

**Comment by virtualex-itv** [comment]
PowerCLI 13 requires you to now install and set your python (v3.7.9) path in order to load the `VMware.ImageBuilder` module.  See [here](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/9619cb6d-3975-4bff-aa1f-0e785283a1a9/58d0925b-e15d-4803-bbd4-eb314dd165b0/GUID-9081EBAF-BF85-48B1-82A0-D1C49F3FF1E8.html) for instructions.

I can confirm that once installed correctly, the script works as expected...

```powershell
ESXi-Customizer-PS> .\ESXi-Customizer-PS.ps1 -v70 -outDir .

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Temporarily logging to C:\Users\virtualex\AppData\Local\Temp\ESXi-Customizer-PS-32788.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.0.0 build 20829139

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-7.0U3si-20841705-standard ...
(Dated 12/08/2022 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 7.0U3si brings whole new levels of virtualization performance to datacenters and enterprises.)

Exporting the Imageprofile to '.\ESXi-7.0U3si-20841705-standard.iso'. Please be patient ...


All done.

(Log file moved to .\ESXi-7.0U3si-20841705-standard.iso-202301271241.log)
```
