### ISSUE TITLE
add driver to  ESXi8.0, error

### ISSUE THREAD

**Issue by gonboy** [VFrontDe/ESXi-Customizer-PS#57]
An unexpected error occurred:
Error retrieving file for VIB 'VMW_bootbank_rste_2.0.2.0088-7vmw.800.1.0.20513097': ('vib20/rste/VMW_bootbank_rste_2.0.2.0088-7vmw.800.1.0.20513097.vib', "Unable to open VIB archive in streaming mode: '_SharedFile' object has no attribute 'writing'").

If requesting support please be sure to include the log file
   y:\temp\ESXi-Customizer-PS-15724.log

**Comment by 617450941** [comment]
my error:
An unexpected error occurred:
Error retrieving file for VIB 'VMware_bootbank_esxio-base_8.0.0-1.0.20513097': ('vib20/esxio-base/VMware_bootbank_esxio-base_8.0.0-1.0.20513097.vib', "Unable to open VIB archive in streaming mode: '_SharedFile' object has no attribute 'writing'").

**Comment by fvlaicu** [comment]
It is a python error, upgrading to 3.7.9 did the trick for me. see more details here:
https://williamlam.com/2022/11/heads-up-unable-to-open-vib-archive-in-streaming-mode-using-export-esximageprofile-with-powercli-13-0.html#comment-67215

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by virtualex-itv** [comment]
> 这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

English please...



> It is a python error, upgrading to 3.7.9 did the trick for me. see more details here: [williamlam.com/2022/11/heads-up-unable-to-open-vib-archive-in-streaming-mode-using-export-esximageprofile-with-powercli-13-0.html#comment-67215](https://williamlam.com/2022/11/heads-up-unable-to-open-vib-archive-in-streaming-mode-using-export-esximageprofile-with-powercli-13-0.html#comment-67215)

correct...closing based off this comment...
