### ISSUE TITLE
error - ESXi 8.0a image not getting created

### ISSUE THREAD

**Issue by stingone** [VFrontDe/ESXi-Customizer-PS#58]
Trying to create an image for latest ESXI 8.0.a however although i have set everhting according documentation incl path to 3.7 etc using latest VMware.PowerCLI 13.0.0.20829139. it give me a lot of error when creating the image and finaly shows at the end.

WARNING:   File path of '/usr/lib/vmware/esxcli/int/lib64/libuser-internal.so' is claimed by multiple non-overlay VIBs:
 {'VMware_bootbank_esx-base_8.0.0-1.10.20842819', 'VMware_bootbank_esxio-base_8.0.0-1.10.20842819'}

An unexpected error occurred:
[WinError 10054] De externe host heeft een verbinding verbroken.

**Comment by virtualex-itv** [comment]
are you running powershell/powercli as an administrator?  This seems like the python path my not be set correctly but I can't tell has I have no clue what you did to set it.  But I can confirm that v2.9.0 of the script works for the latest ESXi 8.0a as I've just tested it...

```powershell
.\ESXi-Customizer-PS.ps1 -v80 -outDir .

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Temporarily logging to C:\Users\virtualex\AppData\Local\Temp\ESXi-Customizer-PS-9992.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.0.0 build 20829139

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-8.0a-20842819-standard ...
(Dated 12/08/2022 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 8.0a brings whole new levels of virtualization performance to datacenters and enterprises.)

Exporting the Imageprofile to '.\ESXi-8.0a-20842819-standard.iso'. Please be patient ...


All done.

(Log file moved to .\ESXi-8.0a-20842819-standard.iso-202301271226.log)
```
