### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by kwdd** [VFrontDe/ESXi-Customizer-PS#60]
Commits:  fa5e39b8fe8e81d2782717676bdec77606e9025e
./ESXi-Customizer-PS.ps1 -v67 -vft  -sip -load net55-r8168
...
Enter selection: ESXi-6.7.0-20220704001-standard
...
An unexpected error occurred:
[WinError 10054] 远程主机强迫关闭了一个现有的连接。

If requesting support please be sure to include the log file
   C:\Users\admin\AppData\Local\Temp\ESXi-Customizer-PS-7516.log

 ESXi-6.7.0-20220604001-standard | ESXi-6.7.0-20220104001-standard |  ESXi-6.7.0-20211104001-standard 都会有报错
 
 
 
C:\Users\admin\AppData\Local\Temp\ESXi-Customizer-PS-7516.log 
```text
Using Imageprofile ESXi-6.7.0-20220704001-standard ...
(Dated 09/21/2022 13:35:37, AcceptanceLevel: PartnerSupported,
Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20220704001-standard)

Load additional VIBs from Online depots ...
   Add VIB net55-r8168 8.045a-napi
 [New AcceptanceLevel: CommunitySupported]
 [OK, added]

Exporting the Imageprofile to 'C:\Users\admin\Downloads\ESXi-Customizer-PS-master\ESXi-Customizer-PS-master\ESXi-6.7.0-20220704001-standard-customized.iso'. Please be patient ...

PS>TerminatingError(Export-EsxImageProfile):“[WinError 10054] 远程主机强迫关闭了一个现有的连接。”
>> TerminatingError(Export-EsxImageProfile):“[WinError 10054] 远程主机强迫关闭了一个现有的连接。”


An unexpected error occurred:
[WinError 10054] 远程主机强迫关闭了一个现有的连接。

If requesting support please be sure to include the log file
   C:\Users\admin\AppData\Local\Temp\ESXi-Customizer-PS-7516.log
```

**Comment by virtualex-itv** [comment]
[Issue 15](https://github.com/VFrontDe-Org/ESXi-Customizer-PS/issues/15)
