### ISSUE TITLE
Failed loading additional VIBs from Online depots in ESXi 8.0

### ISSUE THREAD

**Issue by beeyev** [VFrontDe/ESXi-Customizer-PS#61]
Trying to build custom ESXi 8.0 image with some additional VIBs using this command:
```
.\ESXi-Customizer-PS.ps1 -v80 -vft -load sata-xahci,net55-r8168,net-igb
```
  
  
And getting these errors:
```
Load additional VIBs from Online depots ...
   Add VIB sata-xahci 1.42-1 [New AcceptanceLevel: CommunitySupported] [FAILED, invalid package?]
   Add VIB net55-r8168 8.045a-napi [FAILED, invalid package?]
   Add VIB net-igb 5.3.2-99 [FAILED, invalid package?]
```

This problem is only with ESXi 8.0, with version 7.0 everything is correct.

Is there a way to fix it?

**Comment by ANILuann** [comment]
Hi, could you give me a link to the resulting esxi 7 image?

**Comment by ghost** [comment]
How did you manage to put the net55 8168 driver in esxi 7?

**Comment by beeyev** [comment]
Yes i did, no problem with that.

**Comment by virtualex-itv** [comment]
I highly doubt these were successfully added into ESXi 7.0.  6.x, yes...but not 7.0 or above.  The reason is that those drivers were built using an old Linux kernel that is no longer supported in 7.0 and above.  You can try the Network Community driver which has been productized into 8.0 and see if that works, otherwise, you're out of luck using these older drivers.

**Comment by Rainer6** [comment]
Hello, I do have exactly the same issue with the driver **Net-r8139too** I'm getting the same warning [FAILED, invalid package?]

I need this driver for installation of ESXI 8.0 as a VM in VMM (Virtual Machine Manager on a Synology DiskStation). 

If this driver is not compatible to ESXi 8.0 there are two alternatives connecting the VM to the network: 

**virtio** and **e1000**

do you know if there is a working driver with ESXi 8.0 for those ....??? In the List of currently available ESXi packages there is one driver **Net-e1000e** - does it work with ESXi 8.0 and is it compatible to **e1000** ?

**Comment by virtualex-itv** [comment]
You can try the Network Community driver which has been productized into 8.0 and see if that works, otherwise, you're out of luck using these older drivers.

**Comment by Rainer6** [comment]
Hello Alex,

I tried to build a customized ESXI 8.0-Image including the Network Community driver - I put the vib-file into the pkg-directory

However I got the following error: 

PS C:\VMWare> .\ESXi-Customizer-PS.ps1 -v80 -sip -pkgDir C:\VMWare\pkg -outDir C:\VMWare\ISOs -nsc

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Temporarily logging to C:\Users\rainer\AppData\Local\Temp\ESXi-Customizer-PS-1952.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.1.0 build 21624340

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ...
 [OK]

Select Base Imageprofile:
-------------------------------------------
1 : ESXi-8.0U2-22380479-standard
2 : ESXi-8.0U2-22380479-no-tools
3 : ESXi-8.0U1sc-22082334-standard
4 : ESXi-8.0U1sc-22082334-no-tools
5 : ESXi-8.0U1c-22088125-standard
6 : ESXi-8.0U1c-22088125-no-tools
7 : ESXi-8.0U1a-21813344-standard
8 : ESXi-8.0U1a-21813344-no-tools
9 : ESXi-8.0U1-21495797-standard
10 : ESXi-8.0U1-21495797-no-tools
11 : ESXi-8.0sb-21203431-standard
12 : ESXi-8.0sb-21203431-no-tools
13 : ESXi-8.0c-21493926-standard
14 : ESXi-8.0c-21493926-no-tools
15 : ESXi-8.0b-21203435-standard
16 : ESXi-8.0b-21203435-no-tools
17 : ESXi-8.0a-20842819-standard
18 : ESXi-8.0a-20842819-no-tools
19 : ESXi-8.0.0-20513097-standard
20 : ESXi-8.0.0-20513097-no-tools
-------------------------------------------
Enter selection: 7

Using Imageprofile ESXi-8.0U1a-21813344-standard ...
(Dated 06/01/2023 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 8.0U1a brings whole new levels of virtualization performance to datacenters and enterprises.)

Loading Offline bundles and VIB files from C:\VMWare\pkg ...
   Loading C:\VMWare\pkg\VMW_bootbank_net-community_1.2.7.0-1vmw.700.1.0.15843807.vib ... [OK]
      Add VIB net-community 1.2.7.0-1vmw.700.1.0.15843807 [OK, added]

Exporting the Imageprofile to 'C:\VMWare\ISOs\ESXi-8.0U1a-21813344-standard-customized.iso'. Please be patient ...



An unexpected error occurred:
Error retrieving file for VIB 'VMware_bootbank_crx_8.0.1-0.10.21813344': ('https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/esx/vmw/vib20/crx/VMware_bootbank_crx_8.0.1-0.10.21813344.vib', '', '<urlopen error [Errno 11001] getaddrinfo failed>').

If requesting support please be sure to include the log file
   C:\Users\rainer\AppData\Local\Temp\ESXi-Customizer-PS-1952.log


(Log file moved to C:\VMWare\ISOs\ESXi-8.0U1a-21813344-standard-customized.iso-202310100013.log)
