### ISSUE TITLE
Issues working with local files?

### ISSUE THREAD

**Issue by bbracale** [VFrontDe/ESXi-Customizer-PS#65]
ESXi-Customizer 2.9.0

I have an ISO that I'm trying to use as a base bundle, but I can't figure out the syntax to tell ESXi-Customizer to use it instead of resorting to a repository.  When I use this command line:
PS C:\users\bbracale\Documents\ESXi Customizer> .\ESXi-Customizer-PS.ps1  -pkgDir .\ -load INT_bootbank_igbn_1.4.11.0-1OEM.700.1.0.15525992.vib -izip VMware-VMvisor-Installer-7.0b-16324942.x86_64.iso

I get this error:
Adding base Offline bundle VMware-VMvisor-Installer-7.0b-16324942.x86_64.iso ...Add-EsxSoftwaredepot : Could not download from depot at
file:///C:/users/bbracale/Documents/ESXi%20Customizer/VMware-VMvisor-Installer-7.0b-16324942.x86_64.iso/index.xml,
skipping (('C:\\users\\bbracale\\Documents\\ESXi
Customizer\\VMware-VMvisor-Installer-7.0b-16324942.x86_64.iso\\index.xml', '', '<urlopen error unknown url type: c>'))
At C:\users\bbracale\Documents\ESXi Customizer\ESXi-Customizer-PS.ps1:268 char:22
+     if ($basedepot = Add-EsxSoftwaredepot $izip) {
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (System.String[]:String[]) [Add-EsxSoftwareDepot], Exception
    + FullyQualifiedErrorId : ConnectDepotError,VMware.ImageBuilder.Commands.AddDepot

FATAL ERROR: Cannot add VMware base Offline bundle!

Also, there appears to be a cosmetic when I specify just an offline vib to use.  The script does find the file, but then tries to still aso get it from an Online depot...

PS C:\users\bbracale\Documents\ESXi Customizer> .\ESXi-Customizer-PS.ps1  -v70 -pkgDir .\ -load INT_bootbank_igbn_1.4.11.0-1OEM.700.1.0.15525992.vib

.
.
.
Loading Offline bundles and VIB files from .\ ...
   Loading C:\users\bbracale\Documents\ESXi Customizer\INT_bootbank_igbn_1.4.11.0-1OEM.700.1.0.15525992.vib ... [OK]
      Add VIB igbn 1.4.11.0-1OEM.700.1.0.15525992 [OK, replaced 1.4.11.2-1vmw.703.0.20.19193900]

Load additional VIBs from Online depots ...
   [ERROR] Cannot find VIB named INT_bootbank_igbn_1.4.11.0-1OEM.700.1.0.15525992.vib !

**Comment by virtualex-itv** [comment]
`-izip` doesn't support using an .`iso`.  it's designed to be used with offline bundles ending in a `.zip` extension.  Also, no need to reference the vib within the `-pkgDir`.  Once the param is specified and the path to the folder is added, it will add anything found in the directory
