### ISSUE TITLE
An unexpected error occurred: [PEM: NO_START_LINE] no start line

### ISSUE THREAD

**Issue by nafeasonto** [VFrontDe/ESXi-Customizer-PS#66]
I keep getting this error when I try to download the latest 7.0 ISO.

**Comment by meianhave** [comment]
me too,but i don't think it's the script issue.

**Comment by OhMyGuus** [comment]
Found out that updating Python to V3.7.9 fixes this

**Comment by virtualex-itv** [comment]
python v3.7.9 is a hard requirement for using the ImageBuilder function of PowerCLI...this is not a script issue.
