### ISSUE TITLE
Image Profile fails validation.

### ISSUE THREAD

**Issue by RChadwick7** [VFrontDe/ESXi-Customizer-PS#68]
I'm trying to make a 7.0 image with Realtek drivers in it. I found and downloaded drivers. I can get the ISO created but it gives errors.

When I run this:
 .\ESXi-Customizer-PS.ps1 -v70 -ozip -load net-r8168,net-r8169

I get this:
WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   On platform embeddedEsx, VIB VMware_bootbank_net-r8168_8.013.00-3vmw.510.0.0.799733 requires com.vmware.driverAPI-9.2.1.0, but the requirement cannot be satisfied within the ImageProfile.
WARNING:   On platform embeddedEsx, VIB VMware_bootbank_net-r8169_6.011.00-2vmw.510.0.0.799733 requires com.vmware.driverAPI-9.2.1.0, but the requirement cannot be satisfied within the ImageProfile.
WARNING:   On platform embeddedEsx, VIB VMware_bootbank_net-r8169_6.011.00-2vmw.510.0.0.799733 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.
WARNING:   On platform embeddedEsx, VIB VMware_bootbank_net-r8168_8.013.00-3vmw.510.0.0.799733 requires vmkapi_2_1_0_0, but the requirement cannot be satisfied within the ImageProfile.

When I run this:
.\ESXi-Customizer-PS.ps1 -v70 -pkgDir .\drivers\ -ozip

I get this:
WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   On platform embeddedEsx, VIB Realtek_bootbank_net55-r8168_8.045a-napi requires com.vmware.driverAPI-9.2.2.0, but the requirement cannot be satisfied within the ImageProfile.
WARNING:   On platform embeddedEsx, VIB Realtek_bootbank_net55-r8168_8.045a-napi requires vmkapi_2_2_0_0, but the requirement cannot be satisfied within the ImageProfile.

What am I doing wrong?

**Comment by virtualex-itv** [comment]
The vibs you are using are not compatible with vSphere 7 and higher...check the wiki...
