### ISSUE TITLE
Add VIB net55-r8168 FAILED

### ISSUE THREAD

**Issue by mahdi-azizi** [VFrontDe/ESXi-Customizer-PS#69]
I issiue below command
 .\ESXi-Customizer-PS.ps1 -vft -load net55-r8168

it downloads "ESXi-8.0sb-21203431-standard" automatically and then fails to add network driver

ERROR:
 Add VIB net55-r8168 8.045a-napi [New AcceptanceLevel: CommunitySupported] [FAILED, invalid package?]

**Comment by INTERNETXPL0RER** [comment]
Hi, This isn't a bug.

https://vibsdepot.v-front.de/wiki/index.php/Net55-r8168

Check the "Dependencies and Restrictions" section on the wiki. This driver is only supported on the following versions:
ESXi 5.5, ESXi 6.0, ESXi 6.5, ESXi 6.7

You may consider using an older version

**Comment by virtualex-itv** [comment]
^^ this...
