### ISSUE TITLE
Purple screen on ESXi

### ISSUE THREAD

**Issue by paolokappa** [VFrontDe/ESXi-Customizer-PS#70]
Hi,

I tried your script to create a custom image from the standard VMware one, with the latest update, but when it starts it goes to purple screen :(
I also tried again with other previous versions but the same thing--still purple screen. I preface that the host, with a standard ISO, works perfectly.

PS C:\Downloads> .\ESXi-Customizer-PS.ps1 -izip .\VMware-ESXi-7.0U3i-20842708-depot.zip

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Logging to C:\Users\Kappa\AppData\Local\Temp\ESXi-Customizer-PS-41428.log ...

Running with PowerShell version 7.3 and VMware PowerCLI version 13.1.0 build 21624340

Adding base Offline bundle .\VMware-ESXi-7.0U3i-20842708-depot.zip ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-7.0U3si-20841705-standard ...
(Dated 12/08/2022 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 7.0U3si brings whole new levels of virtualization performance to datacenters and enterprises.)

Exporting the Imageprofile to 'C:\Downloads\ESXi-7.0U3si-20841705-standard.iso'. Please be patient ...

All done.

![photo_2023-05-10_20-20-39](https://github.com/VFrontDe-Org/ESXi-Customizer-PS/assets/7937286/c9206f05-bcb1-4d3c-bdfe-97ab1e93db3e)

**Comment by virtualex-itv** [comment]
Not sure why you are taking one image in the format of a zip bundle and they trying to layer in the "security" updates from the same version.  The zip bundle will already include the security updates.

However, this is not an issue with the script, it already did its magic successfully.
