### ISSUE TITLE
Cant integrate ARECA Drivers to iso

### ISSUE THREAD

**Issue by OliverTempel** [VFrontDe/ESXi-Customizer-PS#71]
`.\ESXi-Customizer-PS.ps1 -v80 -pkgDir C:\tools\drivers -nsc

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Logging to C:\Users\Oliver\AppData\Local\Temp\ESXi-Customizer-PS-29364.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.1.0 build 21624340

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ...
 [OK]

Using Imageprofile ESXi-8.0U1sc-22082334-standard ...
(Dated 07/27/2023 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 8.0U1sc brings whole new levels of virtualization performance to datacenters and enterprises.)

Loading Offline bundles and VIB files from C:\tools\drivers ...
   Loading C:\tools\drivers\arcraid_2.00.00.10-1OEM.700.1.0.15843807_21808248.zip ... [OK]
      Add VIB arcmsrn 2.00.00.08-1OEM.700.1.0.15843807 [OK, added]

Exporting the Imageprofile to 'C:\tools\ESXi-8.0U1sc-22082334-standard-customized.iso'. Please be patient ...

An unexpected error occurred:
Calculated digest at EOF does not match expected result: b4e2f021a258bdf966e1991584066dfcf38190e78ddf4e52fd4014234339f1c3 calculated, 1cb7f47c2e64fe758fe5ad9c9583ada1822fca8724a15d783bc271354f076614 expected.`

**Comment by OliverTempel** [comment]
Have tryed it with V70 and V80, both are stuck at export with EOF Error
Drivers downloaded from areca directly: 
[https://www.areca.com.tw/products/trimode-1886.html](https://www.areca.com.tw/products/trimode-1886.html)

**Comment by virtualex-itv** [comment]
no idea, but this is not an issue with the script.  the script did its magic and is failing to export to a .iso due to a hash check difference.  Double-check that the driver is even supported on v70 or v80 first.  Try to redownload the driver to ensure it is not corrupt.
