### ISSUE TITLE
Error while loading image

### ISSUE THREAD

**Issue by deatlunn-guy** [VFrontDe/ESXi-Customizer-PS#72]
I have an issue while generating a custom image. Log below.

> 
**********************
nStart der Windows PowerShell-Aufzeichnung
Startzeit: 20230920141837
Benutzername: VBHNBK042\VBH-Admin
RunAs-Benutzer: VBHNBK042\VBH-Admin
Konfigurationsname: 
Computer: VBHNBK042 (Microsoft Windows NT 10.0.22621.0)
Hostanwendung: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Prozess-ID: 13508
PSVersion: 5.1.22621.1778
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.1778
BuildVersion: 10.0.22621.1778
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************

Running with PowerShell version 5.1 and VMware PowerCLI version 13.1.0 build 21624340

Connecting the VMware ESXi Software depot ...
 [OK]

Getting Imageprofiles, please wait ...
 [OK]

Using Imageprofile ESXi-7.0U3n-21930508-standard ...
(Dated 07/06/2023 00:00:00, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 7.0U3n brings whole new levels of virtualization performance to datacenters and enterprises.)

Loading Offline bundles and VIB files from D:\distr\esxi\driver ...
   Loading D:\distr\esxi\driver\Net-Community-Driver_1.2.7.0-1vmw.700.1.0.15843807_19480755.zip ...
 [OK]
      Add VIB net-community 1.2.7.0-1vmw.700.1.0.15843807
 [OK, added]
   Loading D:\distr\esxi\driver\net55-r8168-8.045a-napi-offline_bundle.zip ...
 [OK]
      Add VIB net55-r8168 8.045a-napi
 [New AcceptanceLevel: CommunitySupported]
 [OK, added]
   Loading D:\distr\esxi\driver\net55-r8168-8.045a-napi.x86_64.vib ...
 [OK]
      Add VIB net55-r8168 8.045a-napi
 [IGNORED, already added]

Exporting the Imageprofile to 'D:\\ESXi-7.0U3n-21930508-standard-customized.iso'. Please be patient ...

WARNUNG: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNUNG:   On platform embeddedEsx, VIB Realtek_bootbank_net55-r8168_8.045a-napi requires vmkapi_2_2_0_0, but the requirement cannot be satisfied within the ImageProfile. However, additional VIB(s) VMware_bootbank_esx-base_6.7.0-3.185.20491463, VMware_bootbank_esx-base_6.7.0-3.89.15160138, VMware_bootbank_esx-base_6.5.0-3.96.13932383, VMware_bootbank_esx-base_6.7.0-3.123.17098360, VMware_bootbank_esx-base_6.0.0-1.22.3247720, VMware_bootbank_esx-base_5.5.0-2.51.2352327, VMware_bootbank_esx-base_6.5.0-3.149.17167537, VMware_bootbank_esx-base_5.5.0-1.30.1980513, VMware_bootbank_esx-base_6.0.0-2.37.3825889, VMware_bootbank_esx-base_5.5.0-3.89.4179633, VMware_bootbank_esx-base_6.0.0-0.5.2615704, VMware_bootbank_esx-base_5.5.0-1.16.1746018, VMware_bootbank_esx-base_6.7.0-2.52.13473784, VMware_bootbank_esx-base_6.5.0-0.15.5224529, VMware_bootbank_esx-base_6.5.0-0.0.4564106, VMware_bootbank_esx-base_5.5.0-1.25.1892623, VMware_bootbank_esx-base_6.5.0-3.101.14320405, VMware_bootbank_esx-base_6.7.0-1.31.10764712, VMware_bootbank_esx-base_6.5.0-2.88.13635690, VMware_bootbank_esx-base_6.0.0-3.76.6856897, VMware_bootbank_esx-base_6.0.0-0.0.2494585, VMware_bootbank_esx-base_6.5.0-3.116.15256468, VMware_bootbank_esx-base_6.7.0-3.132.17167734, VMware_bootbank_esx-base_6.7.0-3.139.17700514, VMware_bootbank_esx-base_6.7.0-1.44.12986307, VMware_bootbank_esx-base_6.7.0-3.159.18828794, VMware_bootbank_esx-base_5.5.0-2.33.2068190, VMware_bootbank_esx-base_6.7.0-3.143.17700523, VMware_bootbank_esx-base_5.5.0-1.18.1881737, VMware_bootbank_esx-base_6.0.0-3.57.5050593, VMware_bootbank_esx-base_5.5.0-0.8.1474528, VMware_bootbank_esx-base_6.5.0-3.138.16576891, VMware_bootbank_esx-base_6.5.0-3.134.16576879, VMware_bootbank_esx-base_5.5.0-2.62.2718055, VMware_bootbank_esx-base_6.5.0-3.180.19581852, VMware_bootbank_esx-base_5.5.0-2.36.2093874, VMware_bootbank_esx-base_6.5.0-2.50.8294253, VMware_bootbank_esx-base_5.5.0-3.97.4756874, VMware_bootbank_esx-base_6.0.0-0.8.2809111, VMware_bootbank_esx-base_6.7.0-1.41.13004448, VMware_bootbank_esx-base_6.7.0-3.73.14320388, VMware_bootbank_esx-base_6.0.0-1.17.3029758, VMware_bootbank_esx-base_6.7.0-3.128.17167699, VMware_bootbank_esx-base_6.0.0-2.49.4558694, VMware_bootbank_esx-base_6.5.0-2.92.13873656, VMware_bootbank_esx-base_6.0.0-1.29.3568940, VMware_bootbank_esx-base_6.5.0-0.23.5969300, VMware_bootbank_esx-base_6.0.0-1.23.3341439, VMware_bootbank_esx-base_6.0.0-3.69.5572656, VMware_bootbank_esx-base_6.7.0-2.69.14141615, VMware_bootbank_esx-base_6.0.0-3.107.10474991, VMware_bootbank_esx-base_5.5.0-3.103.6480267, VMware_bootbank_esx-base_6.0.0-1.26.3380124, VMware_bootbank_esx-base_5.5.0-3.92.4345810, VMware_bootbank_esx-base_6.5.0-2.75.10884925, VMware_bootbank_esx-base_6.0.0-2.46.4510822, VMware_bootbank_esx-base_5.5.0-3.100.4722766, VMware_bootbank_esx-base_6.0.0-1.31.3568943, VMware_bootbank_esx-base_6.7.0-3.174.19898906, VMware_bootbank_esx-base_5.5.0-0.14.1598313, VMware_bootbank_esx-base_5.5.0-3.117.8934887, VMware_bootbank_esx-base_5.5.0-2.54.2403361, VMware_bootbank_esx-base_6.5.0-3.157.17477841, VMware_bootbank_esx-base_5.5.0-3.84.3568722, VMware_bootbank_esx-base_6.7.0-3.134.17499825, VMware_bootbank_esx-base_6.7.0-2.55.13644319, VMware_bootbank_esx-base_6.5.0-3.161.18071574, VMware_bootbank_esx-base_6.0.0-0.14.3017641, VMware_bootbank_esx-base_5.5.0-3.81.3343343, VMware_bootbank_esx-base_6.5.0-2.79.11925212, VMware_bootbank_esx-base_6.7.0-2.48.13006603, VMware_bootbank_esx-base_6.5.0-3.173.19092475, VMware_bootbank_esx-base_5.5.0-2.55.2456374, VMware_bootbank_esx-base_6.5.0-0.9.4887370, VMware_bootbank_esx-base_6.7.0-3.77.15018017, VMware_bootbank_esx-base_5.5.0-2.65.3029837, VMware_bootbank_esx-base_6.5.0-1.36.7388607, VMware_bootbank_esx-base_6.5.0-2.57.9298722, VMware_bootbank_esx-base_6.5.0-3.111.15177306, VMware_bootbank_esx-base_5.5.0-2.58.2638301, VMware_bootbank_esx-base_5.5.0-0.15.1746974, VMware_bootbank_esx-base_6.5.0-2.67.10719125, VMware_bootbank_esx-base_6.0.0-3.66.5485776, VMware_bootbank_esx-base_6.0.0-3.93.9239792, VMware_bootbank_esx-base_6.5.0-1.29.6765664, VMware_bootbank_esx-base_6.5.0-0.19.5310538, VMware_bootbank_esx-base_6.7.0-3.85.15160134, VMware_bootbank_esx-base_6.0.0-0.6.2715440, VMware_bootbank_esx-base_5.5.0-3.107.7618464, VMware_bootbank_esx-base_5.5.0-2.59.2702869, VMware_bootbank_esx-base_6.0.0-3.72.6765062, VMware_bootbank_esx-base_6.5.0-3.187.19997716, VMware_bootbank_esx-base_6.7.0-0.20.9484548, VMware_bootbank_esx-base_6.0.0-3.135.15018929, VMware_bootbank_esx-base_6.7.0-0.17.9214924, VMware_bootbank_esx-base_5.5.0-3.68.3029944, VMware_bootbank_esx-base_6.5.0-3.184.19588618, VMware_bootbank_esx-base_6.0.0-3.125.14475122, VMware_bootbank_esx-base_6.0.0-3.145.15517548, VMware_bootbank_esx-base_6.0.0-3.100.9313334, VMware_bootbank_esx-base_6.5.0-3.108.14990892, VMware_bootbank_esx-base_6.5.0-0.11.5146843, VMware_bootbank_esx-base_6.5.0-0.14.5146846, VMware_bootbank_esx-base_6.0.0-3.138.15169789, VMware_bootbank_esx-base_5.5.0-3.106.6480324, VMware_bootbank_esx-base_6.5.0-1.26.5969303, VMware_bootbank_esx-base_6.7.0-1.28.10302608, VMware_bootbank_esx-base_6.0.0-3.79.6921384, VMware_bootbank_esx-base_6.7.0-3.104.16075168, VMware_bootbank_esx-base_6.7.0-3.108.16316930, VMware_bootbank_esx-base_6.0.0-3.84.7967664, VMware_bootbank_esx-base_6.5.0-3.146.17097218, VMware_bootbank_esx-base_5.5.0-3.114.7967571, VMware_bootbank_esx-base_5.5.0-3.78.3248547, VMware_bootbank_esx-base_6.0.0-3.129.14513180, VMware_bootbank_esx-base_6.0.0-3.87.8934903, VMware_bootbank_esx-base_6.0.0-3.116.13635687, VMware_bootbank_esx-base_6.7.0-3.178.19997733, VMware_bootbank_esx-base_6.7.0-0.28.10176879, VMware_bootbank_esx-base_6.0.0-3.58.5224934, VMware_bootbank_esx-base_6.7.0-0.14.8941472, VMware_bootbank_esx-base_6.5.0-1.33.7273056, VMware_bootbank_esx-base_5.5.0-3.124.9919047, VMware_bootbank_esx-base_6.7.0-3.112.16701467, VMware_bootbank_esx-base_5.5.0-2.42.2302651, VMware_bootbank_esx-base_6.7.0-0.23.10176752, VMware_bootbank_esx-base_6.0.0-3.96.9239799, VMware_bootbank_esx-base_6.5.0-1.41.7967591, VMware_bootbank_esx-base_6.5.0-3.170.18678235, VMware_bootbank_esx-base_6.5.0-1.47.8285314, VMware_bootbank_esx-base_6.7.0-3.155.18812553, VMware_bootbank_esx-base_6.0.0-0.11.2809209, VMware_bootbank_esx-base_5.5.0-1.28.1892794, VMware_bootbank_esx-base_6.0.0-3.113.13003896, VMware_bootbank_esx-base_6.0.0-2.52.4600944, VMware_bootbank_esx-base_6.5.0-3.143.16901156, VMware_bootbank_esx-base_6.7.0-1.39.11675023, VMware_bootbank_esx-base_6.0.0-2.34.3620759, VMware_bootbank_esx-base_5.5.0-2.39.2143827, VMware_bootbank_esx-base_6.5.0-2.71.10868328, VMware_bootbank_esx-base_6.7.0-3.170.19898894, VMware_bootbank_esx-base_5.5.0-3.86.4179631, VMware_bootbank_esx-base_6.0.0-1.20.3073146, VMware_bootbank_esx-base_6.5.0-3.166.18677441, VMware_bootbank_esx-base_6.5.0-2.83.13004031, VMware_bootbank_esx-base_6.5.0-3.129.16389870, VMware_bootbank_esx-base_6.5.0-2.64.10390116, VMware_bootbank_esx-base_6.5.0-2.61.10175896, VMware_bootbank_esx-base_6.7.0-3.116.16713306, VMware_bootbank_esx-base_6.7.0-3.99.15999342, VMware_bootbank_esx-base_5.5.0-0.0.1331820, VMware_bootbank_esx-base_6.5.0-3.153.17459147, VMware_bootbank_esx-base_6.0.0-3.110.10719132, VMware_bootbank_esx-base_6.5.0-3.191.20448942, VMware_bootbank_esx-base_5.5.0-3.95.4345813, VMware_bootbank_esx-base_5.5.0-1.15.1623387, VMware_bootbank_esx-base_5.5.0-3.101.5230635, VMware_bootbank_esx-base_5.5.0-3.71.3116895, VMware_bootbank_esx-base_5.5.0-0.7.1474526, VMware_bootbank_esx-base_6.5.0-3.195.20502893, VMware_bootbank_esx-base_6.7.0-3.189.20497097, VMware_bootbank_esx-base_6.7.0-3.163.19195723, VMware_bootbank_esx-base_6.7.0-3.120.16773714, VMware_bootbank_esx-base_6.5.0-3.105.14874964, VMware_bootbank_esx-base_6.7.0-3.94.15820472, VMware_bootbank_esx-base_5.5.0-3.75.3247226, VMware_bootbank_esx-base_6.0.0-2.54.5047589, VMware_bootbank_esx-base_6.0.0-2.40.4179598, VMware_bootbank_esx-base_6.7.0-2.60.13981272, VMware_bootbank_esx-base_6.0.0-2.43.4192238, VMware_bootbank_esx-base_6.5.0-3.120.15256549, VMware_bootbank_esx-base_5.5.0-3.120.9313066, VMware_bootbank_esx-base_6.5.0-3.126.16207673, VMware_bootbank_esx-base_6.7.0-0.0.8169922, VMware_bootbank_esx-base_6.5.0-2.54.8935087 from depot can satisfy this requirement.
WARNUNG:   On platform embeddedEsx, VIB Realtek_bootbank_net55-r8168_8.045a-napi requires com.vmware.driverAPI-9.2.2.0, but the requirement cannot be satisfied within the ImageProfile. However, additional VIB(s) VMware_bootbank_misc-drivers_5.5.0-2.62.2718055, VMware_bootbank_misc-drivers_6.0.0-2.43.4192238, VMware_bootbank_misc-drivers_6.0.0-3.79.6921384, VMware_bootbank_misc-drivers_6.0.0-3.69.5572656, VMware_bootbank_misc-drivers_6.0.0-3.96.9239799, VMware_bootbank_misc-drivers_6.0.0-2.52.4600944, VMware_bootbank_misc-drivers_5.5.0-3.68.3029944, VMware_bootbank_misc-drivers_5.5.0-3.95.4345813, VMW_bootbank_shim-vmklinux-9-2-2-0_6.5.0-0.0.4564106, VMware_bootbank_misc-drivers_6.0.0-3.107.10474991, VMW_bootbank_shim-vmklinux-9-2-2-0_6.7.0-0.0.8169922, VMware_bootbank_misc-drivers_5.5.0-3.89.4179633, VMware_bootbank_misc-drivers_5.5.0-0.0.1331820, VMware_bootbank_misc-drivers_6.0.0-0.11.2809209, VMware_bootbank_misc-drivers_6.0.0-3.129.14513180, VMware_bootbank_misc-drivers_5.5.0-2.39.2143827, VMware_bootbank_misc-drivers_5.5.0-2.54.2403361, VMware_bootbank_misc-drivers_5.5.0-3.78.3248547, VMware_bootbank_misc-drivers_6.0.0-2.34.3620759, VMware_bootbank_misc-drivers_6.0.0-3.57.5050593, VMware_bootbank_misc-drivers_6.0.0-3.104.9919195, VMware_bootbank_misc-drivers_5.5.0-1.28.1892794, VMware_bootbank_misc-drivers_5.5.0-0.7.1474526, VMware_bootbank_misc-drivers_6.0.0-0.0.2494585, VMware_bootbank_misc-drivers_6.0.0-1.26.3380124, VMware_bootbank_misc-drivers_6.0.0-1.17.3029758, VMware_bootbank_misc-drivers_5.5.0-2.33.2068190 from depot can satisfy this requirement.
>> TerminatingError(Export-EsxImageProfile): "Calculated digest at EOF does not match expected result: 839b1c293733396a2758991bb721d318325dc48d06d49652ac2cea68f6d8d402 calculated, 1e61f72ce7a9d9c456a4d8fc3fd5e92a59db2af7c4c11c8784dbf51ed274a781 expected."
>> TerminatingError(Export-EsxImageProfile): "Calculated digest at EOF does not match expected result: 839b1c293733396a2758991bb721d318325dc48d06d49652ac2cea68f6d8d402 calculated, 1e61f72ce7a9d9c456a4d8fc3fd5e92a59db2af7c4c11c8784dbf51ed274a781 expected."

An unexpected error occurred:
Calculated digest at EOF does not match expected result: 839b1c293733396a2758991bb721d318325dc48d06d49652ac2cea68f6d8d402 calculated, 1e61f72ce7a9d9c456a4d8fc3fd5e92a59db2af7c4c11c8784dbf51ed274a781 expected.

What can I do?

**Comment by virtualex-itv** [comment]
You cannot add this `net55-r8168` to an ESXi 7.0 or 8.0 image, it will not work as it uses a legacy Linux kernel which is not longer supported in versions of ESXi 7.0 and newer.
