### ISSUE TITLE
Error in line 394

### ISSUE THREAD

**Issue by mbielech5** [VFrontDe/ESXi-Customizer-PS#78]
After running the latest PowerShell script on Windows this evening (11/19/2024 freshly downloaded), the console displays an error in line 394 at character 18:

PS C:\Users\DEVUSER\Desktop\Vmware\esxi-customizer> .\ESXi-Customizer-PS.ps1 -v67 -ozip -pkgDir ./ -load net55-r8168,net51-r8169,net51-sky2,esx-ui,sata-xahci,esxcli-shell,net-e1000e

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Logging to C:\Users\DEVUSER\AppData\Local\Temp\ESXi-Customizer-PS-13068.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 13.3.0 build 24145081

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-6.7.0-20221004001-standard ...
(Dated 09/21/2022 13:35:37, AcceptanceLevel: PartnerSupported,
Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20221004001-standard)
New-EsxImageprofile : Profile ESXi-6.7.0-20221004001-standard-customized is missing component(s) ESXi,Intel-Volume-Mgmt-Device,Intel-ne1000,Mellanox-nmlx5,VMware-NVMeoF-RDMA,VMware-ahci,VMware-iser,VMware-nvme-pcie-plugin,VMw
are-nvme-plugin,VMware-nvmxnet3,VMware-nvmxnet3-ens,VMware-pvscsi,VMware-vmkata,VMware-vmkusb,esx-update which are necesary and removing them is prohibited. Please ensure that these components, which are part of the ESXi
release version 6.7.0-3.189.20497097, are fully installed or overridden without partial VIB replacement or removal.
At C:\Users\DEVUSER\Desktop\Vmware\esxi-customizer\ESXi-Customizer-PS.ps1:394 char:18
+ ... MyProfile = New-EsxImageprofile -CloneProfile $CloneIP -Vendor $ipven ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (VMware.ImageBuilder.Types.ImageProfile:ImageProfile) [New-EsxImageProfile], Exception
    + FullyQualifiedErrorId : EsxImageProfileValidationError,VMware.ImageBuilder.Commands.NewImageProfile

Loading Offline bundles and VIB files from ./ ...

Load additional VIBs from Online depots ...
   [ERROR] Cannot find VIB named net55-r8168 !
   [ERROR] Cannot find VIB named net51-r8169 !
   [ERROR] Cannot find VIB named net51-sky2 !
   Add VIB esx-ui 2.18.0-23593406

An unexpected error occurred:
You cannot call a method on a null-valued expression.

If requesting support please be sure to include the log file
   C:\Users\DEVUSER\AppData\Local\Temp\ESXi-Customizer-PS-13068.log

**Comment by fenghuan1994** [comment]
i have this problem,
how to resolve it?

**Comment by virtualex-itv** [comment]
@mbielech5 @fenghuan1994 - have you tried with the latest powershell 7?
