### ISSUE TITLE
Problems using ESXi-Customizer-PS-v2.6.0

### ISSUE THREAD

**Issue by harshitaggarwal2010** [VFrontDe/ESXi-Customizer-PS#8]
**Sir, I installed the powershell script and run it, but i get following error**

PS>TerminatingError(Export-EsxImageProfile): "[WinError 10054] An existing connection was forcibly closed by the remote host"
>> TerminatingError(Export-EsxImageProfile): "[WinError 10054] An existing connection was forcibly
An unexpected error occured:
[WinError 10054] An existing connection was forcibly closed by the remote host.

**I tried searching on internet but could not get a answer.I want to inject net55-rt8168 driver to esxi 6.5.
Windows 10 (1809, Education version, 64 bit)
Attaching the log files below for both cases, Please help.
[ESXi-Customizer-PS-5592.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/3695980/ESXi-Customizer-PS-5592.log)
[ESXi-Customizer-PS-2924.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/3695981/ESXi-Customizer-PS-2924.log)

**

**Comment by Midriaz** [comment]
This answer can help [https://dev-qa.com/171307/why-run-esxi-customizer-ps-fails-winerror-10054](url) Try to download iso and run the script. I hope it helps.
